### ISSUE TITLE
help for running climatology++ model

### ISSUE THREAD

**Issue by babybearming** [microsoft/subseasonal_toolkit#5]
Thank you for your response,  I run the code "python -m subseasonal_toolkit.generate_predictions -t std_paper_forecast -e -u -m climatology" successfully. But when I run the code "python -m subseasonal_toolkit.generate_predictions -t std_paper_eval -e -u -b -m climpp", there are some errors. What am I not doing right? (results: **The "models" folder appears to be empty, with no "climpp" folder present. Additionally, there seem to be several empty folders within the "eval/metrics/climpp/submodel_forecasts/" directory .**)

**Here are the errors:**
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
Job 1013b638-dd36-a445-4ded-cd7ac72abe54 has started
Log file is located at: /home/metraffic/.azcopy/1013b638-dd36-a445-4ded-cd7ac72abe54.log

100.0 %, 0 Done, 0 Failed, 0 Pending, 0 Total, 2-sec Throughput (Mb/s): 0

Job 1013b638-dd36-a445-4ded-cd7ac72abe54 Summary
Files Scanned at Source: 1
Files Scanned at Destination: 1
Elapsed Time (Minutes): 0.0333
Number of Copy Transfers for Files: 0
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 0
Number of Copy Transfers Completed: 0
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 0
Total Number of Bytes Enumerated: 0
Final Job Status: Completed

elapsed: 5.7759055979549885s
Getting metrics for 2015-01-01 00:00:00
20150101
Warning: models/climpp/submodel_forecasts/climpp-lossrmse_yearsall_margin10/us_tmp2m_1.5x1.5_12w/us_tmp2m_1.5x1.5_12w-20150101.h5 does not exist; skipping
Getting metrics for 2015-01-02 00:00:00

_Originally posted by @babybearming in https://github.com/microsoft/subseasonal_toolkit/issues/4#issuecomment-1612350262_

**Comment by lmackey** [comment]
We believe the last two pushes have fixed this error; please let us know if you have further difficulties!
