### ISSUE TITLE
Informer baseline runtime error

### ISSUE THREAD

**Issue by xuchengong** [microsoft/subseasonal_toolkit#6]
Dear authors, thank you for your work and sharing! 
When I run `informer.ipynb` and `informer.py`, I encounter a shape incompatibility error in the model's forward, and to solve it I locate at `subseasonal_toolkit/models/informer/data/data_loader.py` line 329:
```python
df_raw = data_loaders.get_ground_truth("us_" + self.target, sync=False).reset_index()
```
After I change `"us_" + self.target` to the variable `gt_id`, it works. May I ask whether my modification is correct? Please feel free to point out any of my misunderstanding of the dataset or toolkit. Many thanks!

**Comment by lmackey** [comment]
Thank you for bringing this to our attention.  The latest commit to subseasonal_toolkit/models/informer/data/data_loader.py should fix this issue!
