### ISSUE TITLE
A issue about how to get start 

### ISSUE THREAD

**Issue by XueXianghai** [microsoft/subseasonal_toolkit#7]
When I run the code of 'python -m subseasonal_toolkit.generate_predictions -t std_paper_forecast -e -u -m nn-a' in the cmd. After running for a while ，I see the program has an error of subprocess.CalledProcessError: Command 'azcopy' returned non-zero exit status 2. And   when Getting metrics ，models\nn-a\submodel_forecasts\nn——a_12w_e10001\us_tmp2m_1.5x1.5_12w/us_tmp2m_1.5x1.5_12w-20180101.h5 does not exist; skipping
I want to ask if "I want to ask if my approach about getting started is wrong. Did I miss any steps.

**Comment by notprathap** [comment]
azcopy is a dependency missing in your system.  Depending on your OS, you might have to install it first before being able to run this package.

If you're on Mac like me, you can brew install it

**Comment by geflaspohler** [comment]
@XueXianghai , can you confirm whether installing azcopy resolves your error? Happy to help further if it doesn't.

**Comment by lmackey** [comment]
@XueXianghai, could you also share what operating system you're using?
